version: "3.8"

services:
  pgvector:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flixdin
    network_mode: host
    user: root
    volumes:
      - ./pg_data:/var/lib/postgresql/data
